config/routes.rb
Rails.application.routes.draw do
  resources :feijos

  resources :feijaos

  resources :posts do
    resources :comments, :only => [:create]
  end

  root "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/feijao.rb
class Feijao < ActiveRecord::Base
end

app/models/feijo.rb
class Feijo < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :body
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comments_params)
    redirect_to @post
  end

  private
  def comments_params
    params.require(:comment).permit(:post_id, :body)
  end
end

app/controllers/feijaos_controller.rb
class FeijaosController < ApplicationController
  before_action :set_feijao, only: [:show, :edit, :update, :destroy]

  # GET /feijaos
  # GET /feijaos.json
  def index
    @feijaos = Feijao.all
  end

  # GET /feijaos/1
  # GET /feijaos/1.json
  def show
  end

  # GET /feijaos/new
  def new
    @feijao = Feijao.new
  end

  # GET /feijaos/1/edit
  def edit
  end

  # POST /feijaos
  # POST /feijaos.json
  def create
    @feijao = Feijao.new(feijao_params)

    respond_to do |format|
      if @feijao.save
        format.html { redirect_to @feijao, notice: 'Feijao was successfully created.' }
        format.json { render :show, status: :created, location: @feijao }
      else
        format.html { render :new }
        format.json { render json: @feijao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feijaos/1
  # PATCH/PUT /feijaos/1.json
  def update
    respond_to do |format|
      if @feijao.update(feijao_params)
        format.html { redirect_to @feijao, notice: 'Feijao was successfully updated.' }
        format.json { render :show, status: :ok, location: @feijao }
      else
        format.html { render :edit }
        format.json { render json: @feijao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feijaos/1
  # DELETE /feijaos/1.json
  def destroy
    @feijao.destroy
    respond_to do |format|
      format.html { redirect_to feijaos_url, notice: 'Feijao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feijao
      @feijao = Feijao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feijao_params
      params.require(:feijao).permit(:tipo, :preco)
    end
end

app/controllers/feijos_controller.rb
class FeijosController < ApplicationController
  before_action :set_feijo, only: [:show, :edit, :update, :destroy]

  # GET /feijos
  # GET /feijos.json
  def index
    @feijos = Feijo.all
  end

  # GET /feijos/1
  # GET /feijos/1.json
  def show
  end

  # GET /feijos/new
  def new
    @feijo = Feijo.new
  end

  # GET /feijos/1/edit
  def edit
  end

  # POST /feijos
  # POST /feijos.json
  def create
    @feijo = Feijo.new(feijo_params)

    respond_to do |format|
      if @feijo.save
        format.html { redirect_to @feijo, notice: 'Feijo was successfully created.' }
        format.json { render :show, status: :created, location: @feijo }
      else
        format.html { render :new }
        format.json { render json: @feijo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feijos/1
  # PATCH/PUT /feijos/1.json
  def update
    respond_to do |format|
      if @feijo.update(feijo_params)
        format.html { redirect_to @feijo, notice: 'Feijo was successfully updated.' }
        format.json { render :show, status: :ok, location: @feijo }
      else
        format.html { render :edit }
        format.json { render json: @feijo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feijos/1
  # DELETE /feijos/1.json
  def destroy
    @feijo.destroy
    respond_to do |format|
      format.html { redirect_to feijos_url, notice: 'Feijo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feijo
      @feijo = Feijo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feijo_params
      params.require(:feijo).permit(:tipo, :preco)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feijaos_helper.rb
module FeijaosHelper
end

app/helpers/feijos_helper.rb
module FeijosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
     <p>
       <strong>Posted <%= time_ago_in_words(comment.created_at) %> ago</strong><br/>
        <%= comment.body %>
     </p>
<% end %>

app/views/feijaos/_form.html.erb
<%= form_for(@feijao) do |f| %>
  <% if @feijao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feijao.errors.count, "error") %> prohibited this feijao from being saved:</h2>

      <ul>
      <% @feijao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :preco %><br>
    <%= f.text_field :preco %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feijaos/edit.html.erb
<h1>Editing feijao</h1>

<%= render 'form' %>

<%= link_to 'Show', @feijao %> |
<%= link_to 'Back', feijaos_path %>

app/views/feijaos/index.html.erb
<h1>Listing feijaos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Preco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feijaos.each do |feijao| %>
      <tr>
        <td><%= feijao.tipo %></td>
        <td><%= feijao.preco %></td>
        <td><%= link_to 'Show', feijao %></td>
        <td><%= link_to 'Edit', edit_feijao_path(feijao) %></td>
        <td><%= link_to 'Destroy', feijao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feijao', new_feijao_path %>

app/views/feijaos/new.html.erb
<h1>New feijao</h1>

<%= render 'form' %>

<%= link_to 'Back', feijaos_path %>

app/views/feijaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @feijao.tipo %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @feijao.preco %>
</p>

<%= link_to 'Edit', edit_feijao_path(@feijao) %> |
<%= link_to 'Back', feijaos_path %>

app/views/feijos/_form.html.erb
<%= form_for(@feijo) do |f| %>
  <% if @feijo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feijo.errors.count, "error") %> prohibited this feijo from being saved:</h2>

      <ul>
      <% @feijo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :preco %><br>
    <%= f.text_field :preco %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feijos/edit.html.erb
<h1>Editing feijo</h1>

<%= render 'form' %>

<%= link_to 'Show', @feijo %> |
<%= link_to 'Back', feijos_path %>

app/views/feijos/index.html.erb
<h1>Listing feijos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Preco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feijos.each do |feijo| %>
      <tr>
        <td><%= feijo.tipo %></td>
        <td><%= feijo.preco %></td>
        <td><%= link_to 'Show', feijo %></td>
        <td><%= link_to 'Edit', edit_feijo_path(feijo) %></td>
        <td><%= link_to 'Destroy', feijo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feijo', new_feijo_path %>

app/views/feijos/new.html.erb
<h1>New feijo</h1>

<%= render 'form' %>

<%= link_to 'Back', feijos_path %>

app/views/feijos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @feijo.tipo %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @feijo.preco %>
</p>

<%= link_to 'Edit', edit_feijo_path(@feijo) %> |
<%= link_to 'Back', feijos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<h2>Comments</h2>
 <div id="comments">
  <%= render :partial => @post.comments %>
 </div>

 <%= form_for [@post, Comment.new] do |f| %>
  <p>
     <%= f.label :body, "New comment" %><br/>
     <%= f.text_area :body %>
  </p>
  <p><%= f.submit "Add comment" %></p>
<% end %>